on:
  push:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run "mock" client compilation tests
        uses: ./.github/actions/test-compilation
        with:
          clients: 'all'
          docs-repo: 'datastax/astra-client-docs-tests@master'
          docs-repo-token: ${{ github.token }}
          examples-path: 'resources/mock_examples'
          testing-repo-ref: ${{ github.ref_name || 'master' }}
